from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "DX6i+8n=85jVn9jVL0Ze"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/Users/balazs/elasticsearch-8.6.2/config/certs/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}

# Define index name
index_name = "my_index"

# Define document to be indexed
doc = {
    "title": "My First Elasticsearch Document",
    "text": "This is some sample text that we will use to index our first Elasticsearch document."
}

# Index the document
client.index(index=index_name, body=doc)

# Refresh the index to make it searchable
client.indices.refresh(index=index_name)

# Search for the document
result = client.search(index=index_name, body={"query": {"match_all": {}}})

# Print the results
print("Indexed document:")
for hit in result['hits']['hits']:
    print(f"  title: {hit['_source']['title']}")
    print(f"  text: {hit['_source']['text']}")